application: yyy-question
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /js
  static_dir: js
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest